[versions]
# Gradle Plugins
agp = "8.2.0" # Versão do Android Gradle Plugin (Use uma estável recente)
kotlin = "2.0.0" # Versão do Kotlin (Alinhada com compose-compiler abaixo)
# compose-compiler DEVE ser compatível com a versão do Kotlin
# Para Kotlin 2.0.0 -> use 1.5.11+
compose-compiler = "1.5.11"
# secretsGradlePlugin = "2.0.1" # Descomente se for usar o plugin de secrets

# AndroidX & Compose
coreKtx = "1.13.1"
lifecycleRuntimeKtx = "2.8.1"
activityCompose = "1.9.0"
composeBom = "2024.06.00" # Bill of Materials para Compose

# Networking (Retrofit/OkHttp)
retrofit = "2.9.0" # Versão clássica e estável
okhttp = "4.11.0" # OkHttp (geralmente transitivo, mas bom definir)
converterGson = "2.9.0"

# Testes
junit = "4.13.2"
androidxJunit = "1.1.5" # androidx.test.ext